{% set name = "libprotobuf" %}
{% set version = "3.5.2" %}
{% set sha256 = "4ffd420f39f226e96aebc3554f9c66a912f6cad6261f39f194f16af8a1f6dab2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/google/protobuf/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://github.com/google/googlemock/archive/release-1.7.0.zip
    fn: googlemock-release-1.7.0.zip
    folder: gmock
  - url: https://github.com/google/googletest/archive/release-1.7.0.zip
    fn: googletest-release-1.7.0.zip
    folder: gmock/gtest

build:
  number: 0
  skip: true  # [win and py35]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and (py35 or py36)]

requirements:
  build:
    - toolchain
    - cmake              # [win]
    - autoconf           # [unix]
    - automake           # [unix]
    - libtool            # [unix]
    - pkg-config         # [unix]
    - zlib 1.2.11
    - python             # [win]
    - unzip              # [unix]
  run:
    - zlib 1.2.11

test:
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
    - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME                   # [unix]
    - conda inspect objects -p $PREFIX $PKG_NAME                    # [osx]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format. C++ Libraries"
  description: |
    Protocol buffers are Google's language-neutral,
    platform-neutral, extensible mechanism for serializing structured data-
    think XML, but smaller, faster, and simpler.
  doc_url: https://developers.google.com/protocol-buffers/
  doc_source_url: https://github.com/google/protobuf/releases

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - wesm
    - hajapy
