{% set version = "4.24.1" %}

package:
  name: libprotobuf-suite
  version: {{ version }}

source:
  - url: https://github.com/protocolbuffers/protobuf/archive/v{{ version }}/libprotobuf-v{{ version }}.tar.gz
    sha256: 6a66ed430c8a5c14a4a8ae75bd4d72a155d9444ea1a752355bbb28ea5c414bda
  # these are git submodules from the {{ version }} release
  # https://github.com/protocolbuffers/protobuf/tree/v{{ version }}/third_party
  
  # this submodule is replaced by host dependency
  # - url: https://github.com/abseil/abseil-cpp/archive/c2435f8342c2d0ed8101cb43adfd605fdc52dca2.tar.gz
  #  sha256: 9892836ab0d3f099b8c15076c6f4168144f452d097bd49da215fe0df36a2d48c
  #  folder: third_party/abseil-cpp
  
  # this submodule cannot be replaced by host dependency because lack of such option in CMakeList.txt
  - url: https://github.com/google/googletest/archive/4c9a3bb62bf3ba1f1010bf96f9c8ed767b363774.tar.gz
    sha256: ea54c9845568cb31c03f2eddc7a40f7f83912d04ab977ff50ec33278119548dd
    folder: third_party/googletest

  # this submodule is replaced by host dependency
  #- url: https://github.com/open-source-parsers/jsoncpp/archive/9059f5cad030ba11d37818847443a53918c327b1.tar.gz
  #  sha256: e7a12f50c2125abc9e4b2a38f399393503b6eebd5b4ab75ebb7df1664e768ce7
  #  folder: third_party/jsoncpp

build:
  number: 0

requirements:
  build:  # [linux or (osx and arm64)]
    - sed  # [osx and arm64]

outputs:
  - name: libprotobuf
    script: build-shared.sh  # [unix]
    script: bld-shared.bat  # [win]
    build:
      missing_dso_whitelist:  # [s390x]
        - $RPATH/ld64.so.1    # [s390x]
      run_exports:
        # breaks backwards compatibility and new SONAME each minor release
        # https://abi-laboratory.pro/tracker/timeline/protobuf/
        # One exception was that 3.6.1 was incompatible with 3.6.0
        - {{ pin_subpackage('libprotobuf', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [not win]
        - ninja  # [win]
      host:
        - zlib
        - abseil-cpp 20230802.0
        - jsoncpp 1.9.4
      run:
        - zlib
    test:
      commands:
        - protoc --help
        - test -f ${PREFIX}/lib/libprotobuf${SHLIB_EXT}  # [not win]
        - test ! -f ${PREFIX}/lib/libprotobuf.a  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\libprotoc.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf-lite.lib exit 1  # [win]

  - name: libprotobuf-static
    script: build_static.sh  # [unix]
    script: bld-static.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja  # [win]
        - make  # [not win]
      host:
        - zlib    # [not win]
        - {{ pin_subpackage('libprotobuf', exact=True) }}  # [not win]
      run:
        - zlib    # [not win]
        - {{ pin_subpackage('libprotobuf', exact=True) }}  # [not win]
      run_constrained:
        - libprotobuf <0a0  # [win]
    test:
      commands:
        - test -f ${PREFIX}/lib/libprotobuf.a  # [unix]
        - test -f ${PREFIX}/lib/libprotobuf-lite.a  # [unix]
        - test -f ${PREFIX}/lib/libprotoc.a  # [unix]
        - if exist %PREFIX%\\Library\\bin\\libprotoc.dll exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\libprotoc.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf-lite.lib exit 1  # [win]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Protocol Buffers - Google's data interchange format. C++ Libraries and protoc, the protobuf compiler.
  description: |
    Protocol buffers are Google's language-neutral,
    platform-neutral, extensible mechanism for serializing structured data-
    think XML, but smaller, faster, and simpler.
  dev_url: https://github.com/protocolbuffers/protobuf
  doc_url: https://developers.google.com/protocol-buffers/

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - ocefpaf
    - wesm
    - hajapy
    - xhochy
