# keep this without major version to let the bot pick it up
{% set version = "33.0" %}
# protobuf doesn't add the major version in the tag, it's defined per language in
# https://github.com/protocolbuffers/protobuf/blob/main/version.json
{% set major = "6" %}

{% set libraries = ["libprotoc", "libprotobuf", "libprotobuf-lite"] %}
# different patterns between unix & windows
{% set utf8_libraries = ["libutf8_range", "libutf8_validity"] %}     # [unix]
{% set utf8_libraries = ["utf8_range", "utf8_validity"] %}           # [win]

package:
  name: libprotobuf-split
  version: {{ major ~ "." ~ version }}

source:
  - url: https://github.com/protocolbuffers/protobuf/archive/refs/tags/v{{ version.replace(".rc", "-rc") }}.tar.gz
    sha256: b6b03fbaa3a90f3d4f2a3fa4ecc41d7cd0326f92fcc920a7843f12206c8d52cd
    patches:
      - patches/0001-set-static-lib-extension-on-windows.patch
      - patches/0002-always-look-for-shared-abseil-builds.patch
      - patches/0003-do-not-install-vendored-gmock.patch
      # skip annoyingly flaky test on windows, see
      # https://github.com/protocolbuffers/protobuf/issues/8645
      - patches/0004-disable-MapImplTest.RandomOrdering-due-to-flakiness.patch      # [win]
      # necessary for building grpc
      - patches/0005-export-symbols-needed-by-grpc.patch
      # protobuf does a non-standard `libfoo.dll` naming pattern for protobuf;
      # for now, we avoid extending it to utf8_range, because (despite correct CMake
      # metadata), other libraries - not least grpcio - are still expecting to find
      # utf8_range.{dll,lib}, not libutf8_range.{dll,lib}.
      - patches/0006-do-not-add-LIB_PREFIX-to-utf8_-range-validity-on-win.patch     # [win]
      - patches/0007-Workaround-nvcc-bug-in-message_lite.h.patch

build:
  number: 0
 
outputs:
  - name: libprotobuf
    script: build-lib.sh  # [unix]
    script: build-lib.bat  # [win]
    build:
      missing_dso_whitelist:  # [s390x]
        - $RPATH/ld64.so.1    # [s390x]
      run_exports:
        # protobuf now (intentionally) increments the SOVER with every patch release, which
        # breaks tools like grpc_plugin_cpp if they get the wrong libprotoc at runtime, see
        # https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4075
        - {{ pin_subpackage('libprotobuf', max_pin='x.x.x') }}
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx and x86_64]
      ignore_run_exports_from:
        - gtest
        - jsoncpp
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja-base
      host:
        - gtest {{ gtest }}
        - jsoncpp {{ jsoncpp }}
        - libabseil {{ libabseil }}
        # requires abseil test targets to build with tests enabled
        - libabseil-tests
        - zlib {{ zlib }}
      run:
        - zlib       # bounds through run_exports
        - libabseil  # bounds through run_exports        
        # following google's C++ support policy, protobuf only support MacOS >=10.13, see:
        # https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md
        # https://github.com/protocolbuffers/protobuf/blob/v24.0/Protobuf-C%2B%2B.podspec#L29
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx and x86_64]
    test:
      requires:
        # cmake needs compiler to be able to run package detection, see
        # https://discourse.cmake.org/t/questions-about-find-package-cli-msvc/6194
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja-base
        - pkg-config
      files:
        - cmake_test/
      commands:
        {% for each_lib in libraries + utf8_libraries%}
        # shared libraries
        - test -f ${PREFIX}/lib/{{ each_lib }}.so                      # [linux]
        - test -f ${PREFIX}/lib/{{ each_lib }}.dylib                   # [osx]
        - if not exist %LIBRARY_BIN%\{{ each_lib }}.dll exit 1         # [win]
        - if not exist %LIBRARY_LIB%\{{ each_lib }}.lib exit 1         # [win]

        # absence of static libraries
        - test ! -f ${PREFIX}/lib/{{ each_lib }}.a                     # [unix]
        - if exist %LIBRARY_LIB%\{{ each_lib }}-static.lib exit 1      # [win]
        {% endfor %}

        # cmake
        - test -f ${PREFIX}/lib/cmake/protobuf/protobuf-config.cmake              # [unix]
        - if not exist %LIBRARY_LIB%\cmake\protobuf\protobuf-config.cmake exit 1  # [win]

        # pkg-config
        - pkg-config --print-errors --exact-version "{{ version }}.0" protobuf
        - pkg-config --print-errors --exact-version "{{ version }}.0" protobuf-lite

        # binary
        - protoc --help

        # more CMake integration
        - cd cmake_test
        - cmake -GNinja $CMAKE_ARGS .   # [unix]
        - cmake -GNinja %CMAKE_ARGS% .  # [win]
        - cmake --build .

  - name: libprotobuf-static
    script: build-lib.sh  # [unix]
    script: build-lib.bat  # [win]
    build:
      always_include_files:
        # Must overwrite the CMake metadata from shared libprotobuf
        - lib/cmake/protobuf/           # [unix]
        - Library/lib/cmake/protobuf/   # [win]
      ignore_run_exports_from:
        - jsoncpp
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja-base
      host:
        - gtest {{ gtest }}
        - jsoncpp {{ jsoncpp }}
        - libabseil {{ libabseil }}
        # requires abseil test targets to build with tests enabled
        - libabseil-tests {{ libabseil }}
        - zlib {{ zlib }}
        - {{ pin_subpackage('libprotobuf', exact=True) }}
      run:
        - zlib       # bounds through run_exports
        - libabseil  # bounds through run_exports
        - {{ pin_subpackage('libprotobuf', exact=True) }}
    test:
      requires:
        # cmake needs compiler to be able to run package detection, see
        # https://discourse.cmake.org/t/questions-about-find-package-cli-msvc/6194
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja-base
      files:
        - cmake_test/
      commands:
        {% for each_lib in libraries %}
        # static libraries
        - test -f ${PREFIX}/lib/{{ each_lib }}.a                       # [unix]
        - if not exist %LIBRARY_LIB%\{{ each_lib }}-static.lib exit 1  # [win]
        {% endfor %}

        # more CMake integration
        - cd cmake_test
        - cmake -GNinja $CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release .  # [unix]
        - cmake -GNinja %CMAKE_ARGS% -DCMAKE_BUILD_TYPE=Release . # [win]
        - cmake --build . --config Release

  - name: libprotobuf-python-headers
    script: build-pyheaders.sh  # [unix]
    script: build-pyheaders.bat  # [win]
    requirements:
      host:
        - {{ pin_subpackage('libprotobuf', exact=True) }}
      run_constrained:
        - libprotobuf {{ major ~ "." ~ version }}
    test:
      commands:
        - test -f $PREFIX/include/google/protobuf/proto_api.h      # [unix]
        - test -f $PREFIX/include/google/protobuf/pyext/message.h  # [unix]
        - if not exist %LIBRARY_PREFIX%\include\google\protobuf\proto_api.h exit 1      # [win]
        - if not exist %LIBRARY_PREFIX%\include\google\protobuf\pyext\message.h exit 1  # [win]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Protocol Buffers - Google's data interchange format. C++ Libraries and protoc, the protobuf compiler.
  description: |
    Protocol buffers are Google's language-neutral,
    platform-neutral, extensible mechanism for serializing structured data-
    think XML, but smaller, faster, and simpler.
  dev_url: https://github.com/protocolbuffers/protobuf
  doc_url: https://developers.google.com/protocol-buffers/

extra:
  recipe-maintainers:
    - JohanMabille
    - jjerphan
    - xylar
    - dopplershift
    - jakirkham
    - ocefpaf
    - wesm
    - hajapy
    - xhochy
    - h-vetinari
  feedstock-name: libprotobuf
