{% set version = "3.15.8" %}

package:
  name: libprotobuf-suite
  version: {{ version }}

source:
  - url: https://github.com/protocolbuffers/protobuf/archive/v{{ version }}/protobuf-v{{ version }}.tar.gz
    sha256: 0cbdc9adda01f6d2facc65a22a2be5cecefbefe5a09e5382ee8879b522c04441
    patches:
      - 0001-remove-Werror-from-test-flags.patch  # [ppc64le or aarch64 or s390x]
      - 0002-remove-failing-json-parser-test.patch  # [s390x]
      # our build machine does not have enough memory for this test.
      # see: https://github.com/protocolbuffers/protobuf/issues/8082
      - 0003-remove-large-output-test.patch         # [s390x]
      # This issue gets fixed and then reintroduced often
      # https://github.com/protocolbuffers/protobuf/issues/7567
      #- issue-7567.patch
  # these are git submodules from the 3.10.1 release
  # https://github.com/protocolbuffers/protobuf/tree/v3.10.1/third_party
  - url: https://github.com/google/benchmark/archive/5b7683f49e1e9223cf9927b24f6fd3d6bd82e3f8.tar.gz
    sha256: 0cbdc9adda01f6d2facc65a22a2be5cecefbefe5a09e5382ee8879b522c04441
    folder: third_party/benchmark
  - url: https://github.com/google/googletest/archive/5ec7f0c4a113e2f18ac2c6cc7df51ad6afc24081.tar.gz
    sha256: 0cbdc9adda01f6d2facc65a22a2be5cecefbefe5a09e5382ee8879b522c04441
    folder: third_party/googletest

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - ninja  # [win]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - unzip  # [not win]
    - make  # [not win]
  host:
    - zlib

outputs:
  - name: libprotobuf
    script: build_shared.sh  # [unix]
    script: build_shared.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake  # [win]
        - ninja  # [win]
        - autoconf  # [not win]
        - automake  # [not win]
        - libtool  # [not win]
        - pkg-config  # [not win]
        - unzip  # [not win]
        - make  # [not win]
      host:
        - zlib
    build:
      number: 0
      run_exports:
        # breaks backwards compatibility and new SONAME each minor release
        # https://abi-laboratory.pro/tracker/timeline/protobuf/
        # One exception was that 3.6.1 was incompatible with 3.6.0
        - {{ pin_subpackage('libprotobuf', max_pin='x.x') }}
    test:
      commands:
        - protoc --help
        - test -f ${PREFIX}/lib/libprotobuf${SHLIB_EXT}  # [not win]
        - test ! -f ${PREFIX}/lib/libprotobuf.a  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\libprotoc.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf-lite.lib exit 1  # [win]

  - name: libprotobuf-static
    script: build_static.sh  # [unix]
    requirements:
      build:
        # This ensures correct build order.
        - {{ pin_subpackage('libprotobuf', exact=True) }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake  # [win]
        - ninja  # [win]
        - autoconf  # [not win]
        - automake  # [not win]
        - libtool  # [not win]
        - pkg-config  # [not win]
        - unzip  # [not win]
        - make  # [not win]
      host:
        - zlib
    build:
      skip: true  # [win]
      number: 0
    test:
      commands:
        - test -f ${PREFIX}/lib/libprotobuf.a  # [unix]
        - test -f ${PREFIX}/lib/libprotobuf-lite.a  # [unix]
        - test -f ${PREFIX}/lib/libprotoc.a  # [unix]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Protocol Buffers - Google's data interchange format. C++ Libraries and protoc, the protobuf compiler.
  description: |
    Protocol buffers are Google's language-neutral,
    platform-neutral, extensible mechanism for serializing structured data-
    think XML, but smaller, faster, and simpler.
  doc_url: https://developers.google.com/protocol-buffers/
  doc_source_url: https://github.com/protocolbuffers/protobuf/releases

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - wesm
    - hajapy
    - xhochy
