{% set name = "libprotobuf" %}
{% set version = "3.6.0" %}
# git commit corresponding to the v3.6.0 tag
{% set commit = "ab8edf1dbe2237b4717869eaab11a2998541ad8d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/google/protobuf.git
  git_rev: {{ commit }}
  patches:
    - 2614.patch
    - 0001-remove-Werror-from-test-flags.patch  # [ppc64le]

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    # breaks backwards compatibility and new SONAME each minor release
    # 3.6.1 also appears to change SONAME from 3.6.0*
    # https://abi-laboratory.pro/tracker/timeline/protobuf/
    - {{ pin_subpackage('libprotobuf', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake              # [win]
    - autoconf           # [unix]
    - automake           # [unix]
    - libtool            # [unix]
    - pkg-config         # [unix]
    - unzip              # [unix]
    - make               # [unix]
  host:
    - zlib

test:
  commands:
    - protoc --help
    - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
    - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
    - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]

about:
  home: https://developers.google.com/protocol-buffers/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Protocol Buffers - Google's data interchange format. C++ Libraries"
  description: |
    Protocol buffers are Google's language-neutral,
    platform-neutral, extensible mechanism for serializing structured data-
    think XML, but smaller, faster, and simpler.
  doc_url: https://developers.google.com/protocol-buffers/
  doc_source_url: https://github.com/google/protobuf/releases

extra:
  recipe-maintainers:
    - dopplershift
    - jakirkham
    - jjhelmus
    - ocefpaf
    - wesm
    - hajapy
